name: esptool as a pio tool

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install --upgrade platformio

      - name: Build firmware
        run: /opt/hostedtoolcache/Python/3.12.7/x64/bin/pio pkg exec --package "platformio/tool-esptoolpy" -- esptool version