name: esptool as a pio tool

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python3 -m pip install -U platformio

      - name: Build firmware
        run: pio pkg exec --package "platformio/tool-esptoolpy@~1.40501.0" -- esptool.py version