name: esptool as a python tool

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install esptool

      - name: Build firmware
        run: python -m esptool --chip esp32 merge_bin --output output.bin 0x1000 test1.bin 0x2000 test2.bin